### ISSUE TITLE
Asset not found

### ISSUE THREAD

**Issue by Awea** [nightsailer/padrino-sprockets#10]
Hi guys,

I just follow the README to use your gem inside a new fresh Padrino app but I can't get assets so what i'm missing ?

**Comment by wikimatze** [comment]
Hi @Awea, do you still have those issues? I've written a blog post about using it for JS and CSS files http://wikimatze.de/using-sprockets-to-manage-the-asset-pipeline-in-padrino.html - maybe this can solve your problems.

Please close the issue, if it is now working for you.

Best wishes from Berlin

Matthias
