### ISSUE TITLE
Minifying javascript - use yuicompressor gem to minify javascript instead of jsmin gem

### ISSUE THREAD

**Issue by gregjopa** [nightsailer/padrino-sprockets#17]
The jsmin gem hasn't been updated in a long time and the author says not to use it in his readme file: https://github.com/rgrove/jsmin/#readme. I'm running into issues with this jsmin gem with minifying twitter boostrap's js plugins (missing semicolon fun). 

How do you feel about removing jsmin and using the yuicompressor gem for minifying js instead? I can take a stab at creating a pull request for this if you're willing to commit it.

**Comment by wikimatze** [comment]
Hi @gregjopa would be nice, if you could do this please. I'm still thinking to write tests for this plugin but find it very hard to start with. Feel free to give a foundation for this.

Thanks for contributing and hard work!
