### ISSUE TITLE
Upload 0.0.3 version to rubygems.org

### ISSUE THREAD

**Issue by gregjopa** [nightsailer/padrino-sprockets#19]
Can you please upload the 0.0.3 version of padrino-sprockets to rubygems?

**Comment by wikimatze** [comment]
@nightsailer can you bump the new version? I tested it!

**Comment by dmyers** [comment]
Bump. @nightsailer it would be appreciated! :+1:

**Comment by dmyers** [comment]
@matthias-guenther Is the author still maintaining? I see he merged your commits, but hasn't updated Ruby Gems. I can't use GitHub as the source in my Gemfile.

**Comment by wikimatze** [comment]
Hi @dmyers, I contacted @nightsailer about giving me the gem push rights for it, but he didn't respond so far - maybe he is too busy. Should I contact the rubygems persons and ask them to give me the rights?

**Comment by dmyers** [comment]
Oh good idea. Dang. Yeah that might work.

**Comment by wikimatze** [comment]
Posted a tweet to ask about how to do it.

**Comment by wikimatze** [comment]
Nobody answered but here is the link and option I've found http://guides.rubygems.org/command-reference/#gem_owner

**Comment by nightsailer** [comment]
Upload is just done.

Sorry, everybody, I'd forgot to update rubygems after merged on github ;-(

**Comment by wikimatze** [comment]
Thanks for your response, I'll close this issue now. And thanks for putting me as an owner of this gem on the list. So I can release future versions of it, if there is a need for an additional need.

**Comment by dmyers** [comment]
Thanks guys! Much appreciated. :+1:
