### ISSUE TITLE
Server side caching

### ISSUE THREAD

**Issue by dmyers** [nightsailer/padrino-sprockets#23]
Could there be a way to set the cache store for Sprockets for where it should do server side caching? It appears to be an option in the `Sprockets::Environment`.

http://blog.alexmaccaw.com/faster-deploys

**Comment by skamansam** [comment]
I created a pull request #28 which for code which allows you to modify the Sprockets environment in the `sprockets` method, so you can use:

``` ruby
      sprockets :minify=>true , :js_compressor => UglifierWithSourceMapCompressor do |env|
        env.css_compressor = :scss
        env.cache = Sprockets::Cache::MemcacheStore.new # from link
      end
```

I would love it if you could test it out and see if it suits your needs.
