### ISSUE TITLE
Ability to get environment to be able to manually configure

### ISSUE THREAD

**Issue by dmyers** [nightsailer/padrino-sprockets#25]
What do you think?

**Comment by skamansam** [comment]
I like this idea. I plan on implementing this on my fork. I will put in a Pull Request when I am done.

**Comment by skamansam** [comment]
Pull Request #28 resolves this. You can do the following in your app.rb, you can now pass a block to `sprockets` which allows you to edit the Sprockets Environment, as such:

``` ruby
     sprockets :minify=>true , :js_compressor => UglifierWithSourceMapCompressor do |env|
        env.css_compressor = :scss

        # from http://blog.alexmaccaw.com/faster-deploys
        env.cache = Sprockets::Cache::MemcacheStore.new 
      end
```

I would love it if you could test it out for me and let me know if it suits your needs.
